# Generated by Django 6.0.5 on 2026-05-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('premium', 'Suite Premium'), ('presidencial', 'Suite Presidencial'), ('ecologica', 'Cabaña Ecológica'), ('estandar', 'Habitación Estándar')], max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField()),
                ('amenities', models.TextField(help_text='Separadas por comas')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
