# Generated by Django 6.0.5 on 2026-05-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tag',
            field=models.CharField(choices=[('suite', 'Suite Premium'), ('presidencial', 'Suite Presidencial'), ('cabana', 'Cabaña Ecológica'), ('estandar', 'Habitación Estándar')], max_length=30),
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='hotel.habitacion')),
            ],
        ),
    ]
