# Generated by Django 6.0.5 on 2026-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservacion',
            name='hora_llegada',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='peticiones',
            field=models.TextField(blank=True),
        ),
    ]
