# Generated by Django 6.0.5 on 2026-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('limpieza', 'Limpieza')], default='libre', max_length=20),
        ),
    ]
